
!include common.yaml
---
- package: R module prodlim
  name: prodlim
  rpkgname: prodlim
  version: "{{versions.prodlim}}"
  baseurl: https://cran.r-project.org/src/contrib
  src_tarball: "{{rpkgname}}_{{version}}.{{extension}}"
  vendor_source: "{{baseurl}}/{{rpkgname}}_{{version}}.{{extension}}"
  requires:
    - R_{{Rversion}}
    - R_{{Rversion}}-Rcpp
    - R_{{Rversion}}-data_table
    - R_{{Rversion}}-diagram
    - R_{{Rversion}}-lava
    - R_{{Rversion}}-shape
    - R_{{Rversion}}-future_apply
    - R_{{Rversion}}-numDeriv
    - R_{{Rversion}}-progressr
    - R_{{Rversion}}-SQUAREM
    - R_{{Rversion}}-future
    - R_{{Rversion}}-globals
    - R_{{Rversion}}-digest
    - R_{{Rversion}}-listenv
    - R_{{Rversion}}-parallelly
