
!include common.yaml
---
- package: R module pkgconfig
  name: pkgconfig
  rpkgname: pkgconfig
  version: "{{versions.pkgconfig}}"
  baseurl: https://cran.r-project.org/src/contrib
  src_tarball: "{{rpkgname}}_{{version}}.{{extension}}"
  vendor_source: "{{baseurl}}/{{rpkgname}}_{{version}}.{{extension}}"
  requires:
    - R_{{Rversion}}
