
!include common.yaml
---
- package: R module prodlim
  name: prodlim
  rpkgname: prodlim
  version: "{{versions.prodlim}}"
  baseurl: https://cran.r-project.org/src/contrib
  src_tarball: "{{rpkgname}}_{{version}}.{{extension}}"
  vendor_source: "{{baseurl}}/{{rpkgname}}_{{version}}.{{extension}}"
  requires:
    - R_{{Rversion}}
    - R_{{Rversion}}-Rcpp
    - R_{{Rversion}}-lava
    - R_{{Rversion}}-numDeriv
    - R_{{Rversion}}-SQUAREM
